name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    # nothing here

jobs:
  build-linux:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y ninja-build

      - name: Configure CMake
        run: cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build build --target vtf-thumbnailer --config ${{matrix.build_type}}

      - name: Create Installer
        working-directory: build
        run: cpack

      - name: Upload Release
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: 'VTF-Thumbnailer-Linux'
          path: |
            build/*.deb
          retention-days: 7

  build-kde5:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y ninja-build extra-cmake-modules libkf5kio-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{github.workspace}}/qt'
          modules: ${{env.QT_MODULES}}
          cache: true

      - name: Configure CMake
        run: cmake -G "Ninja" -B build -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix` -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DQT_MAJOR_VERSION="5" -DQt5_DIR="${{github.workspace}}/qt" -DVTF_THUMBNAILER_BUILD_KDE_PLUGIN=ON

      - name: Build
        run: cmake --build build --target vtf-thumbnailer --config ${{matrix.build_type}}

      - name: Create Installer
        working-directory: build
        run: cpack

      - name: Upload Release
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: 'VTF-Thumbnailer-KDE5'
          path: |
            build/*.deb
          retention-days: 7

  build-kde6:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y ninja-build kf6-extra-cmake-modules kf6-kio-devel

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{github.workspace}}/qt'
          modules: ${{env.QT_MODULES}}
          cache: true

      - name: Configure CMake
        run: cmake -G "Ninja" -B build -DCMAKE_INSTALL_PREFIX=`kf6-config --prefix` -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DQT_MAJOR_VERSION="6" -DQt6_DIR="${{github.workspace}}/qt" -DVTF_THUMBNAILER_BUILD_KDE_PLUGIN=ON

      - name: Build
        run: cmake --build build --target vtf-thumbnailer --config ${{matrix.build_type}}

      - name: Create Installer
        working-directory: build
        run: cpack

      - name: Upload Release
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: 'VTF-Thumbnailer-KDE6'
          path: |
            build/*.deb
          retention-days: 7

  build-windows:
    if: false # disable for now
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true

      - name: Configure CMake
        run: cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build build --target vtf-thumbnailer --config ${{matrix.build_type}}

      - name: Create Installer
        if: matrix.build_type == 'Release'
        working-directory: build
        run: cpack

      - name: Upload Release
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: 'VTF-Thumbnailer-Windows'
          path: |
            build/*.exe
          retention-days: 7
